apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: simplenodejs-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "172.17.17.109"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: simplenodejs
spec:
  hosts:
  - "*"
  gateways:
  - simplenodejs-gateway
  http:
  - route:
    - destination:
        host: simplenodejs
        subset: v1
      weight: 70
    - destination:
        host: simplenodejs
        subset: v2
      weight: 30

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: simplenodejs
spec:
  host: simplenodejs
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2