apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-v4
  labels:
    version: v4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplenodejs
      version: v2
  template:
    metadata:
      labels:
        app: simplenodejs
        version: v2
    spec:
      containers:
      - name: nodejs
        image: raguyazhin/simple-node-app:4.0.0
        ports:
        - containerPort: 3000