apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-v3
  labels:
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplenodejs
      version: v1
  template:
    metadata:
      labels:
        app: simplenodejs
        version: v1
    spec:
      containers:
      - name: nodejs
        image: raguyazhin/simple-node-app:3.0.0
        ports:
        - containerPort: 3000